export const initialState = [
    {
      id: 1,
      imageURL: "https://source.unsplash.com/featured/?electronics",
      name: "Product 1",
      category: "Electronics",
      price: 199.99,
      quantity: 50,
    },
    {
      id: 2,
      imageURL: "https://source.unsplash.com/featured/?clothing",
      name: "Product 2",
      category: "Clothing",
      price: 49.99,
      quantity: 100,
    },
    {
      id: 3,
      imageURL: "https://source.unsplash.com/featured/?homeandgarden",
      name: "Product 3",
      category: "Home and Garden",
      price: 129.99,
      quantity: 30,
    },
    {
      id: 4,
      imageURL: "https://source.unsplash.com/featured/?beauty",
      name: "Product 4",
      category: "Beauty",
      price: 79.99,
      quantity: 75,
    },
    {
      id: 5,
      imageURL: "https://source.unsplash.com/featured/?sports",
      name: "Product 5",
      category: "Sports",
      price: 59.99,
      quantity: 60,
    },
    {
      id: 6,
      imageURL: "https://source.unsplash.com/featured/?toys",
      name: "Product 6",
      category: "Toys",
      price: 39.99,
      quantity: 120,
    },
    {
      id: 7,
      imageURL: "https://source.unsplash.com/featured/?books",
      name: "Product 7",
      category: "Books",
      price: 24.99,
      quantity: 90,
    },
    {
      id: 8,
      imageURL: "https://source.unsplash.com/featured/?kitchen",
      name: "Product 8",
      category: "Kitchen",
      price: 149.99,
      quantity: 40,
    },
    {
      id: 9,
      imageURL: "https://source.unsplash.com/featured/?furniture",
      name: "Product 9",
      category: "Furniture",
      price: 299.99,
      quantity: 25,
    },
    {
      id: 10,
      imageURL: "https://source.unsplash.com/featured/?health",
      name: "Product 10",
      category: "Health",
      price: 89.99,
      quantity: 70,
    },
  ];